import re

RULES: list[tuple[str, list[str]]] = [
    (
        "Groceries",
        [
            "whole foods",
            "trader joe",
            "safeway",
            "kroger",
            "ralph",
            "vons",
            "albertson",
            "sprouts",
            "hmart",
            "h mart",
            "99 ranch",
            "99ranch",
            "smart final",
            "costco",
            "sam's club",
            "aldi",
            "publix",
            "wegman",
            "fresh market",
            "market basket",
            "stop shop",
            "grocery",
            "marukai",
            "raley's",
            "weee inc",
            "mitsuwa",
            "nijiya",
            "99 market",
            "ranch market",
            "food 4 less",
            "food maxx",
            "winco",
        ],
    ),
    (
        "Dining",
        [
            # chains
            "starbucks",
            "mcdonald",
            "chipotle",
            "subway",
            "domino",
            "pizza",
            "taco bell",
            "burger king",
            "wendy",
            "chick-fil-a",
            "panda express",
            "in-n-out",
            "five guys",
            "shake shack",
            "popeye",
            "dunkin",
            "doordash",
            "uber eats",
            "ubereats",
            "grubhub",
            "postmates",
            "instacart restaurant",
            "seamless",
            "yelp food",
            # generic
            "cafe",
            "bakery",
            "restaurant",
            "sushi",
            "ramen",
            "pho",
            "boba",
            "thai",
            "dim sum",
            "diner",
            "bistro",
            "kitchen",
            "grill",
            "eatery",
            "bar & grill",
            "noodle",
            "hotpot",
            "bbq",
            "dumpling",
            "burger",
            "taqueria",
            "tacos",
            "curry",
            "udon",
            "izakaya",
            "brasserie",
            "trattoria",
            "pizzeria",
            "steakhouse",
            "seafood",
            # POS system prefixes used by restaurants
            "tst*",  # Toast POS
            "uep*",  # Union Pay restaurant
            "snack*",  # Snack food marketplace
            "par*marugame",
            "par*",  # PAR POS
            # local / specific
            "aki japanese",
            "bongo burger",
            "daimo",
            "heytea",
            "hashi",
            "impression of lanzhou",
            "meet fresh",
            "mollyteapaloalto",
            "mollytea",
            "muncho noodles",
            "my o my",
            "my.o.my",
            "nippon curry",
            "qahwa time",
            "tang jip",
            "tap haus",
            "the cheese board",
            "toss noodle",
            "uji time",
            "yang sheng tang",
            "yin ji",
            "zhangliang",
            "wushiland",
            "gordon ramsay",
            "marugame",
            "hankki",
            "noodleosophy",
            "malatown",
            "yifang",
            "mochiholic",
            "chicha san chen",
            "everytable",
            "jungdon katsu",
            "blue bottle coffee",
            "seoul hotdog",
            "yalis",
            "boba guys",
            "ike's love",
            "philz",
            "peet's",
            "coffee bean",
            "la boulangerie",
            "tartine",
            "b-patisserie",
            "otter* eat",
            "snack* ",
            "3cat handcrafte",
            "xpression",
            "le dessert",
            "boardwalk food",
            "beers",
            "brewery",
            "illy caffe",
            "mugu boka",
            "the noodle",
            "secrets of tiger",
            "ben ben hot pot",
            "crawlsf",
        ],
    ),
    (
        "Travel",
        [
            "uber",
            "lyft",
            "bart ",
            "caltrain",
            "muni ",
            "metro",
            "transit",
            "parking",
            "chevron",
            "shell",
            "exxon",
            "bp gas",
            "76 ",
            "arco",
            "speedway",
            "circle k",
            "sunoco",
            "valero",
            "marathon gas",
            "enterprise rent",
            "hertz",
            "avis",
            "budget rent",
            "zipcar",
            "fastrak",
            "ez-pass",
            "ezpass",
            "toll",
            "amtrak",
            "greyhound",
            "united air",
            "delta air",
            "southwest air",
            "american air",
            "jetblue",
            "alaska air",
            "spirit air",
            "frontier",
            # local parking
            "pmusa",
            "laz pkg",
            "laz parking",
            "parksmart",
            "pzg**",
            "prkg ips mete",
            "berkeley-prkg",
            "impark",
            "parkng",
            "park meter",
            # gas stations
            "telegraph gas",
            "us pro gas",
            "alaska gasoline",
            "gulf oil",
            "berkeley gas",
            # ride/taxi
            "curb lv",
            "desert cab",
            "yellow cab",
            "taxi",
            "ca dmv",
            "dmv ",
            "vehicle reg",  # DMV fees
            "PMUSA",
        ],
    ),
    (
        "Shopping",
        [
            "amazon",
            "amzn",
            "target",
            "walmart",
            "best buy",
            "apple store",
            "apple.com",
            "costco",
            "home depot",
            "lowes",
            "ikea",
            "tj maxx",
            "marshalls",
            "ross store",
            "nordstrom",
            "macy",
            "gap ",
            "old navy",
            "h&m",
            "zara",
            "uniqlo",
            "nike",
            "adidas",
            "ebay",
            "etsy",
            "wayfair",
            "overstock",
            "chewy",
            "petco",
            "petsmart",
            "daiso",
            "dollar tree",
            "dollartree",
            "five below",
            "ace hdwe",
            "ace hardware",
            "rex key",
            "the ups store",
            "usps po",
            "ups*",
            "ups store",
            "segway",
            "g2abvshop",
        ],
    ),
    (
        "Entertainment",
        [
            "netflix",
            "hulu",
            "disney+",
            "disneyplus",
            "hbo",
            "peacock",
            "paramount",
            "spotify",
            "apple music",
            "tidal",
            "pandora",
            "youtube",
            "twitch",
            "steam ",
            "playstation",
            "xbox",
            "nintendo",
            "amc theatre",
            "amc ",
            "regal cinema",
            "cinemark",
            "jack london",
            "ticketmaster",
            "stubhub",
            "tickpick",
            "eventbrite",
            "fandango",
            "crawlsf",
            "raven bar",
            "nayax amusement",
            "de young",
            "legion museum",
            "stanford athlet",
            "su athltcs",
            "santa cruz beach",
            "24 hours of lemons",
            "raceways",
            "raceway",
            "monroe",
            "anshundainc",
        ],
    ),
    (
        "Health",
        [
            "cvs",
            "walgreen",
            "rite aid",
            "duane reade",
            "pharmacy",
            "kaiser",
            "sutter health",
            "ucsf",
            "stanford health",
            "one medical",
            "doctor",
            "dentist",
            "optometrist",
            "hospital",
            "clinic",
            "urgent care",
            "lab corp",
            "quest diagnostics",
            "gym",
            "planet fitness",
            "24 hour fitness",
            "la fitness",
            "orange theory",
            "equinox",
            "peloton",
            "weight watchers",
            "hair salon",
            "nail salon",
            "sayu hair",
            "beauty",
            "ucb recreational sport",
        ],
    ),
    (
        "Utilities",
        [
            "pg&e",
            "pge ",
            "at&t",
            "verizon",
            "t-mobile",
            "comcast",
            "xfinity",
            "spectrum",
            "cox cable",
            "directv",
            "dish network",
            "ting ",
            "electricity",
            "water bill",
            "gas bill",
            "internet",
            "phone bill",
            "mint mobile",
            "expressvpn",
            "nordvpn",
            "vpn",
        ],
    ),
    (
        "Housing",
        [
            "rent",
            "mortgage",
            "hoa ",
            "zillow",
            "apartment",
            "property",
            "airbnb",
            "vrbo",
            "hotel",
            "hyatt",
            "marriott",
            "hilton",
            "holiday inn",
            "sheraton",
            "westin",
            "inelle hotel",
            "wash kiosk",
            "jen-hao chen",
        ],
    ),
    (
        "Education",
        [
            "tuition",
            "university",
            "college",
            "coursera",
            "udemy",
            "linkedin learning",
            "skillshare",
            "chegg",
            "student loan",
            "textbook",
            "bookstore",
            "ucb housing",
            "uc berkeley cal dining",
            "ucb housing&dining",
            "uc berkeley",
            "cal dining",
        ],
    ),
    (
        "Insurance",
        [
            "geico",
            "state farm",
            "allstate",
            "progressive",
            "farmers insurance",
            "liberty mutual",
            "usaa",
            "nationwide",
            "insurance",
            "insur ",
            "blue shield",
            "blue cross",
            "anthem",
            "cigna",
            "aetna",
            "united health",
            "covered ca",
            "health plan",
            "dental plan",
            "vision plan",
        ],
    ),
    (
        "Investment",
        [
            "schwab",
            "fidelity",
            "vanguard",
            "merrill",
            "robinhood",
            "etrade",
            "td ameritrade",
            "wealthfront",
            "betterment",
            "acorns",
            "manual db-bkrg",
            "manual cr-bkrg",
            "brokerage",
            "investing",
            "anthropic",
            "claude sub",  # AI subscriptions
            "investment",
            "capital one",
        ],
    ),
]

CATEGORY_COLORS = {
    "Groceries": "#4CAF50",
    "Dining": "#FF5722",
    "Travel": "#2196F3",
    "Shopping": "#9C27B0",
    "Entertainment": "#FF9800",
    "Health": "#00BCD4",
    "Utilities": "#607D8B",
    "Housing": "#795548",
    "Education": "#3F51B5",
    "Insurance": "#E91E63",
    "Investment": "#009688",
    "Other": "#757575",
}

ALL_CATEGORIES = list(CATEGORY_COLORS.keys())


def categorize(description: str) -> str:
    desc = description.lower()
    for category, keywords in RULES:
        for kw in keywords:
            if kw in desc:
                return category
    return "Other"


def infer_tx_type(description: str, amount: float, account_type: str) -> str:
    """
    amount here is the already-stored value (sign already flipped for credit cards by parser):
      credit card:  amount < 0 = purchase/expense, amount > 0 = payment or refund
      checking:     amount > 0 = deposit/income,   amount < 0 = debit/expense
    """
    desc = description.lower()
    if account_type == "credit":
        if amount > 0:
            if any(
                kw in desc
                for kw in [
                    "automatic payment",
                    "payment - thank",
                    "payment thank you",
                    "autopay",
                    "mobile payment",
                ]
            ):
                return "payment"
            return "income"  # merchant refund / statement credit
        else:
            return "expense"
    else:
        # ── checking outflows (amount < 0) ────────────────────────────────
        # Zelle/Venmo/CashApp to other people = expense by default (paying someone)
        _TRANSFER_OUT = [
            "transfer to",
            "wire transfer",
            "online transfer",
            "discover",  # credit card payment
            "chase credit crd",  # Chase credit card autopay from checking
            "payment to chase card",  # explicit Chase card payment
            "autopay",  # any credit card autopay
            "ach debit",
            "capital one",  # transfers to Capital One savings / investments
            "manual db-bkrg",  # manual debit to brokerage (investment contribution)
        ]
        # ── checking inflows (amount > 0) ─────────────────────────────────
        _INCOME_IN = [
            "direct dep",
            "direct deposit",
            "direct pay",  # e.g. "Uc Berkeley Direct Pay"
            "payroll",
            "gusto",
            "adp ",
            "paychex",
            "ach credit",
            "venmo from",
            "cashapp from",
            "interest paid",
            "interest earned",
            "tax refund",
            "irs",
            "remote online deposit",  # check/mobile deposits
        ]
        # ── brokerage credits back (positive = transfer back from brokerage) ──
        _TRANSFER_IN = [
            "manual cr-bkrg",
            "brokerage",
        ]
        # ── Zelle inflows from self or known shared-expense contacts → transfer ──
        _ZELLE_SELF_FROM = [
            "weishan weng",
        ]

        if amount > 0:
            if any(kw in desc for kw in _TRANSFER_IN):
                return "transfer"
            # Zelle from self = moving money between own accounts
            if "zelle payment from" in desc and any(
                kw in desc for kw in _ZELLE_SELF_FROM
            ):
                return "transfer"
            if any(kw in desc for kw in _INCOME_IN):
                return "income"
            if "zelle payment from" in desc:
                return "income"  # Zelle from someone else = reimbursement / income
            return "transfer"  # unrecognised positive = transfer (conservative)
        else:
            if any(kw in desc for kw in _TRANSFER_OUT):
                return "transfer"
            return "expense"
